version: '3'

services:
  sink:
    image: "ghcr.io/nabeken/docker-smtp-sink:latest"
    volumes:
      - "/sink"
    command: [-v, -h, mx.example.com, -m, '100', ':10025', '100']
    ports:
      - "10025:10025"
  bench:
    build: "."
    depends_on:
      - sink
    command: /root/bench.sh
