name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run bench
      run: |
        docker compose build
        docker compose run --rm bench /root/bench_check.sh

