name: Go

on:
  - push
  - pull_request

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: '1.21.0'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: '${{ env.GO_VERSION }}'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Run bench
      run: |
        docker compose build
        docker compose run --rm bench /root/bench_check.sh

