name: Release

on:
  push:
    tags:
       - 'v0.*'

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: '1.22.2'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: '${{ env.GO_VERSION }}'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
